# Change these first
owner: Hylosium # Your GitHub organization or username, where this repository lives
repo: test-uptimee # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Kagi
    url: https://kagi.com/
    description: "Though it's a paid service, the results are better than anyone else."
  - name: marginalia
    url: https://marginalia-search.com/
    description: "Independent search engine made correctly, like the old days."
  - name: Overleaf (GUI self-hosted)
    url: https://gui.inf.uva.es/
  - name: Frontend (GUI)
    url: https://gui.inf.uva.es/
  #- name: IPv6 test
    #url: forwardemail.net
    #port: 80
    #check: "tcp-ping"
    #ipv6: true
 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /test-uptimee
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** es un monitor de uptime y página de estado open-source, gestionado completamente por GitHub."
  introMessage: Estado en tiempo real desde [GitHub](https://github.com/Hylosium/test-uptimee). Sin servidores, solo GitHub Actions. [**Crea la tuya gratis**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  # ...


workflowSchedule:
  graphs: "0 0 * * *"             # Ejecutar una vez al día a medianoche
  responseTime: "0 23 * * *"       # Ejecutar una vez al día a las 11 PM
  staticSite: "0 1 * * *"          # Ejecutar una vez al día a la 1 AM
  summary: "0 0 * * *"             # Ejecutar una vez al día a medianoche
  updateTemplate: "0 0 * * *"      # Ejecutar una vez al día a medianoche
  updates: "0 3 * * *"             # Ejecutar una vez al día a las 3 AM
  uptime: "*/5 * * * *"              # Ejecutar una vez cada hora (debido a la limitación de GitHub Actions gratis)
  
